#ifndef SCENE_TYPE_H
#define SCENE_TYPE_H

enum class SceneType {
    HOUSE,
    LEADERBOARD,
    COMPUTER,
    WINDOW,
    WARDROBE,
    MINIGAMES_SELECTOR,
    MINIGAME_CONSTRUCTION_1,
    MINIGAME_CONSTRUCTION_2,
    MINIGAME_CONSTRUCTION_3,
    MINIGAME_CONSTRUCTION_4,
    MINIGAME_CONSTRUCTION_5,
    MINIGAME_PIZZA_1,
    MINIGAME_2,
    MINIGAME_BAR_1,
    MINIGAME_COFFEE_1
};

#endif